<a href="https://colab.research.google.com/github/k-yena/math/blob/main/Numpy_%EB%B0%B0%EC%97%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 빠른 연산을 위한 NumPy

In [10]:
import numpy as np

In [6]:
arr1 = np.array([1,2,3])

In [7]:
arr1.shape

(3,)

In [8]:
type(arr1)

numpy.ndarray

In [9]:
arr1.ndim

1

In [10]:
arr1[0]

1

In [11]:
arr1_1 = np.array([1,'two', 3])

In [12]:
arr1_1

array(['1', 'two', '3'], dtype='<U21')

In [13]:
arr2 = np.array([[1,2,3], [1,2,3]])

In [14]:
arr2

array([[1, 2, 3],
       [1, 2, 3]])

In [15]:
arr3 = np.array([[[1,2,3], [1,2,3]],[[1,2,3], [1,2,3]]])

In [16]:
arr3

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [17]:
arr3.shape

(2, 2, 3)

In [18]:
arr_tu = np.array((1,2,3))

In [19]:
arr_tu

array([1, 2, 3])

In [20]:
np.array(arr_tu)

array([1, 2, 3])

In [21]:
np.array({1,1,4,4,5})

array({1, 4, 5}, dtype=object)

In [22]:
np.array({'a': 'apple','b':'banana'})

array({'a': 'apple', 'b': 'banana'}, dtype=object)

In [23]:
np.arange(10)     # arange  -->  numpy의 range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(1,10+1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
np.arange(1,10+1,3)

array([ 1,  4,  7, 10])

In [26]:
np.array([1,'a',True])

array(['1', 'a', 'True'], dtype='<U21')

In [27]:
arr_test = np.array([1,'a',True])

In [28]:
type(arr_test[0])

numpy.str_

In [29]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [30]:
np.linspace(1,10, num=1000)

array([ 1.        ,  1.00900901,  1.01801802,  1.02702703,  1.03603604,
        1.04504505,  1.05405405,  1.06306306,  1.07207207,  1.08108108,
        1.09009009,  1.0990991 ,  1.10810811,  1.11711712,  1.12612613,
        1.13513514,  1.14414414,  1.15315315,  1.16216216,  1.17117117,
        1.18018018,  1.18918919,  1.1981982 ,  1.20720721,  1.21621622,
        1.22522523,  1.23423423,  1.24324324,  1.25225225,  1.26126126,
        1.27027027,  1.27927928,  1.28828829,  1.2972973 ,  1.30630631,
        1.31531532,  1.32432432,  1.33333333,  1.34234234,  1.35135135,
        1.36036036,  1.36936937,  1.37837838,  1.38738739,  1.3963964 ,
        1.40540541,  1.41441441,  1.42342342,  1.43243243,  1.44144144,
        1.45045045,  1.45945946,  1.46846847,  1.47747748,  1.48648649,
        1.4954955 ,  1.5045045 ,  1.51351351,  1.52252252,  1.53153153,
        1.54054054,  1.54954955,  1.55855856,  1.56756757,  1.57657658,
        1.58558559,  1.59459459,  1.6036036 ,  1.61261261,  1.62

In [31]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
arr3

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [36]:
arr3[0][1][1:]

array([2, 3])

In [37]:
# 형변환

In [38]:
# int,str, float, bool

In [39]:
#   정수, 실수 --> 문자
#  문자 --> 정수, 실수

In [40]:
str(np. array([2,3]))

'[2 3]'

In [41]:
arr_int = np. array([2,3])

In [42]:
arr_int.astype('str')

array(['2', '3'], dtype='<U21')

In [43]:
arr_str = arr_int.astype('str')

In [44]:
arr_str

array(['2', '3'], dtype='<U21')

In [45]:
arr_str.dtype

dtype('<U21')

In [46]:
arr_str[0].dtype

dtype('<U1')

In [47]:
arr_str = np.array(['1','2'])

In [48]:
arr_str

array(['1', '2'], dtype='<U1')

In [49]:
arr_str.astype('int')

array([1, 2])

In [50]:
arr_str.astype('int')+1

array([2, 3])

In [51]:
arr_str.astype('float')+1

array([2., 3.])

In [52]:
np.arange(1,6+1)

array([1, 2, 3, 4, 5, 6])

In [53]:
np.arange(1,6+1).reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
np.arange(1,6+1).reshape((2,3)).reshape((6,))

array([1, 2, 3, 4, 5, 6])

In [55]:
np.arange(1,6+1).reshape((2,3)).reshape((6))

array([1, 2, 3, 4, 5, 6])

In [56]:
arr_2d = np.arange(1,6+1).reshape((2,3))

In [57]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
arr_2d.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [59]:
np.array([[1,3,5],[2,4,6]])

array([[1, 3, 5],
       [2, 4, 6]])

In [60]:
np.array([[1,3,5],[2,4,6]]).reshape(6)

array([1, 3, 5, 2, 4, 6])

In [61]:
ap = np.array([[[1,2,3], [4,5,6]],[[7,8,9], [10,11,12]]])

In [62]:
ap = np.array([[[1,2,3], [4,5,6]],[[7,8,9], [10,11,12]]])

In [63]:
ap.shape

(2, 2, 3)

In [64]:
ap.reshape(1,12)       # ap.reshape(-1,12)과 같은 의미

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [65]:
ap.reshape(-1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [66]:
ap.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
import random

In [68]:
random.random()

0.8043790485896037

In [69]:
np.random.rand()

0.10827455300892497

In [70]:
np.random.randn()

0.01458238068596903

In [71]:
[np.random.randn() for i in range(1000)]

[-0.7431172306304267,
 0.7686357010792939,
 1.114128572418318,
 -0.5830893538652927,
 0.38190957579897633,
 -1.3669245469818236,
 -0.9146029914165311,
 0.1443379174111144,
 1.2403982791352484,
 1.6296548666385824,
 -1.689401589934023,
 1.7714880308333858,
 -0.30192742849723775,
 2.6721512142164086,
 0.2664615550597519,
 0.7697970704673328,
 -1.4540748313433953,
 -0.04649440788221719,
 -1.3924585591694048,
 -1.1592559753788658,
 -2.0999900099439475,
 0.6688475016106958,
 0.20147615124677917,
 -1.3212524178047194,
 0.8046060519067612,
 -0.20769399588124643,
 -0.5547624211130378,
 -0.8068422850023905,
 0.8651576273370628,
 -0.9532663869867396,
 0.9147611190826955,
 0.8166494772810224,
 -0.4590586038601369,
 0.09997486774800021,
 0.7645809652658694,
 -1.1148500060261304,
 0.6643174497575669,
 0.702407409940067,
 0.6383729672464874,
 -0.4723451482075802,
 -1.2915372456760983,
 -0.955727908266541,
 -0.027856058988609166,
 -2.071182544271736,
 0.7715418772824979,
 -0.18829157411824324,
 2.258

In [72]:
np.mean([np.random.randn() for i in range(1000)])  # 0에 가깝게 나옴

0.02385785915026081

In [73]:
np.mean([np.random.randn() for i in range(10000)])

0.009367195483497704

In [74]:
np.mean([np.random.randn() for i in range(10000000)])

0.00014335746545681276

In [75]:
np.var([np.random.randn() for i in range(1000)])

1.0478759806685431

In [76]:
np.var([np.random.randn() for i in range(10000)])

0.9846511172465445

In [78]:
np.random.randn(2,3)

array([[ 0.48072664,  1.61322596, -0.40409094],
       [-0.07903841,  1.2168347 , -2.21649821]])

In [11]:
%time for i in range(1000) : np.arange(100000)*2

CPU times: user 134 ms, sys: 421 µs, total: 135 ms
Wall time: 138 ms


In [12]:
%time for i in range(1000) : list(range(100000))*2

CPU times: user 2.96 s, sys: 12.5 ms, total: 2.98 s
Wall time: 3 s


In [14]:
a = np.array([1,2,3])

In [15]:
np.append(a, [4,5,6])

array([1, 2, 3, 4, 5, 6])

In [17]:
a2 = np.append(a, [4,5,6])

In [18]:
a2

array([1, 2, 3, 4, 5, 6])

In [19]:
help(np.append)

Help on _ArrayFunctionDispatcher in module numpy:

append(arr, values, axis=None)
    Append values to the end of an array.
    
    Parameters
    ----------
    arr : array_like
        Values are appended to a copy of this array.
    values : array_like
        These values are appended to a copy of `arr`.  It must be of the
        correct shape (the same shape as `arr`, excluding `axis`).  If
        `axis` is not specified, `values` can be any shape and will be
        flattened before use.
    axis : int, optional
        The axis along which `values` are appended.  If `axis` is not
        given, both `arr` and `values` are flattened before use.
    
    Returns
    -------
    append : ndarray
        A copy of `arr` with `values` appended to `axis`.  Note that
        `append` does not occur in-place: a new array is allocated and
        filled.  If `axis` is None, `out` is a flattened array.
    
    See Also
    --------
    insert : Insert elements into an array.
    delet

In [21]:
np.append(a, [7], axis=0)

array([1, 2, 3, 7])

In [22]:
np.append(a, [7], axis=1)     # 차원이 맞지 않음

AxisError: axis 1 is out of bounds for array of dimension 1

In [36]:
np.append(a.reshape(3,-1), [[7]], axis=0)

array([[1],
       [2],
       [3],
       [7]])

In [37]:
np.append(a.reshape(3,-1), [[7],[7],[7]], axis=1)

array([[1, 7],
       [2, 7],
       [3, 7]])

In [24]:
a.reshape(3,-1)

array([[1],
       [2],
       [3]])

In [26]:
a_re = a.reshape(3,-1)

In [27]:
a_re

array([[1],
       [2],
       [3]])

In [31]:
a_re.ndim

2

In [33]:
np.append(a_re, [[7],
                 [8],
                 [9]], axis=0)

array([[1],
       [2],
       [3],
       [7],
       [8],
       [9]])

In [34]:
np.append(a_re, [[7],
                 [8],
                 [9]], axis=1)

array([[1, 7],
       [2, 8],
       [3, 9]])